
stages:
    - build
    - deploy

Pulling code for dev:
    stage: build
    script:
        - cd ~/public_html 
        #- git reset --hard
        - git pull origin development        
    only:
        - development

Pulling code for stage:
    stage: build
    script:
        - cd ~/public_html/ismo
        #- git reset --hard
        - git pull origin staging
    only:
        - staging

Deploy:
    stage: deploy
    script:
        - php artisan migrate
        - php artisan queue:restart
    only:
        - development
        - staging