
stages:
    - build
    - deploy

Pulling code for dev:
    stage: build
    variables:
        GIT_STRATEGY: none
    script:
        - cd /home/dev-ismo/public_html 
        #- git reset --hard
        - sudo git pull origin development        
    only:
        - development

Pulling code for stage:
    stage: build
    variables:
        GIT_STRATEGY: none
    script:
        - cd /home/ismo/public_html/ismo
        #- git reset --hard
        - sudo git pull origin staging
    only:
        - staging

Deploy Dev:
    stage: deploy
    variables:
        GIT_STRATEGY: none
    script:
        - cd /home/dev-ismo/public_html 
        - sudo composer dump-autoload
        - php artisan migrate
        - php artisan queue:restart
    only:
        - development

Deploy Stage:
    stage: deploy
    variables:
        GIT_STRATEGY: none
    script:
        - cd /home/ismo/public_html/ismo
        - sudo composer dump-autoload
        - php artisan migrate
        - php artisan queue:restart
    only:
        - staging